# Generated by Django 2.0.6 on 2019-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190407_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='TODO', max_length=50),
        ),
    ]
